### PR TITLE
Created basic Moisture Activity

### PR DESCRIPTION
**Pull request by ThomasGhys2540**
[Create Moisture Activity](https://app.gitkraken.com/glo/view/card/e0671ea5cbc046c393995d3ac707e4a0)

### CODE REVIEW

**Comment by AlfianSanjaya** [comment]
I see you added some buttons to the layout, but I don't see any buttons on it? Buttons are like invisible or something
image

image

**Comment by ThomasGhys2540** [comment]
Wait whut.....

**Comment by AlfianSanjaya** [comment]
Nevermind it's fixed haha
image

**Comment by AlfianSanjaya** [comment]
Are the buttons only for visual purposes or are we planning to do something with the moisture sensors buttons in the near future?

**Comment by ThomasGhys2540** [comment]
At the moment only for visual purposes but I was thinking we could use the buttons as a way to go to a new activity/screen with more info of each sensor

**Review by AlfianSanjaya — APPROVED** [review]
Looks good

**Review by ThomasKramp — APPROVED** [review]
Naast de gridlayout die moeilijk doet is dit goed. We kunnen niet meer doen zonder de input van de finnen.

**Pull request merged**
