### PR TITLE
Improve List Functions

### PR DESCRIPTION
**Pull request by ThomasKramp**
Changing the items by clicking them

### CODE REVIEW

**Review by ThomasGhys2540 — COMMENTED** [review]
The clicking and deleting works nicely, but I found out that when someone enters a value that's bigger than what the int can manage it just doesn't recognise it as a change. Maybe add a catch for that kind of behaviour?

**Review by AlfianSanjaya — APPROVED** [review]
It's running smoothly. Editing the items is also a nice touch!

**Comment by ThomasGhys2540** [comment]
Okay that works! approved for merging into QA.

**Review by AlfianSanjaya — APPROVED** [review]
Good

**Pull request merged**
